insert into messages (MESSAGEID, SUBSCRIBERID, MESSAGENAME, MULTICAST, MESSAGEURL, MESSAGETEXT, DISPLAYDATETIME, IMMEDIATELY, AUTOHIDETIME, EXPIRATIONDATETIME, STATUS, ACTIVATIONDATETIME, CREATIONDATETIME, MESSAGETYPE, POPUPMESSAGE, POPUPMESSAGETEXT) values('79','23','UNICASTMSG','1','http://<host>:<port>/','str1asd234','1494225222',NULL,'30','2123390022','0','1494495973','1494495973','Product','1','str12asd34');
insert into messages (MESSAGEID, SUBSCRIBERID, MESSAGENAME, MULTICAST, MESSAGEURL, MESSAGETEXT, DISPLAYDATETIME, IMMEDIATELY, AUTOHIDETIME, EXPIRATIONDATETIME, STATUS, ACTIVATIONDATETIME, CREATIONDATETIME, MESSAGETYPE, POPUPMESSAGE, POPUPMESSAGETEXT) values('64','23','UNICASTMSG','1','http://<host>:<port>/','str1asd234','1494225222',NULL,'30','2123390022','1','1494495973','1494495973','Product','1','str12asd34');
insert into stbaddressing (ID, MACADDRESS, MESSAGEID, MESSAGESTATUS) values('11','MAC1114','64',NULL);
insert into stbaddressing (ID, MACADDRESS, MESSAGEID, MESSAGESTATUS) values('12','MAC1113','64',NULL);
insert into stbaddressing (ID, MACADDRESS, MESSAGEID, MESSAGESTATUS) values('11','MAC1114','79',NULL);
insert into stbaddressing (ID, MACADDRESS, MESSAGEID, MESSAGESTATUS) values('11','MAC1113','79',NULL);
INSERT INTO MESSAGETYPES (ID, MESSAGETYPE) VALUES (1, 'Product');
INSERT INTO MESSAGETYPES (ID, MESSAGETYPE) VALUES (2, 'Service');
INSERT INTO MESSAGETYPES (ID, MESSAGETYPE) VALUES (3, 'CTA');
insert into filters(MESSAGEID,IPADDRESS,PACKAGEID,WATCHEDCHANNELID,LOCATIONID,SOFTWAREVERSION,UIVERSION,CURRENTUILANGUAGE,HARDWAREVERSION,FIPSCODE) values(79,'0.0.1.1','pkg-1','chn-1','loc-1','sw-1','ui-1','clang-1','hw-1','fips-1');
insert into filters(MESSAGEID,IPADDRESS,PACKAGEID,WATCHEDCHANNELID,LOCATIONID,SOFTWAREVERSION,UIVERSION,CURRENTUILANGUAGE,HARDWAREVERSION,FIPSCODE) values(79,'0.0.1.2','pkg-2','chn-2','loc-2','sw-2','ui-2','clang-2','hw-2','fips-2');
insert into filters(MESSAGEID,IPADDRESS,PACKAGEID,WATCHEDCHANNELID,LOCATIONID,SOFTWAREVERSION,UIVERSION,CURRENTUILANGUAGE,HARDWAREVERSION,FIPSCODE) values(2,'0.0.1.3','pkg-3','chn-3','loc-3','sw-3','ui-2','clang-3','hw-2','fips-12');

commit;




