--
-- Current Database: pushmessaging
--

DROP DATABASE IF EXISTS `pushmessaging`;

CREATE DATABASE `pushmessaging` CHARACTER SET utf8 COLLATE utf8_bin;

USE `pushmessaging`;

--
-- Table structure for table `MESSAGES`
--

CREATE TABLE `MESSAGES` (		      
	`MESSAGEID` int(11) NOT NULL AUTO_INCREMENT,
	`SUBSCRIBERID` varchar(100) DEFAULT NULL,
	`MESSAGENAME` varchar(75) DEFAULT NULL, 
	`MULTICAST` tinyint(1) DEFAULT NULL,    
	`MESSAGEURL` varchar(1000) DEFAULT NULL,
	`MESSAGETEXT` varchar(1024) DEFAULT NULL,
	`DISPLAYDATETIME` bigint(20) DEFAULT NULL,          
	`IMMEDIATELY` tinyint(1) DEFAULT NULL,   
	`AUTOHIDETIME` int(3) DEFAULT NULL, 
	`EXPIRATIONDATETIME` bigint(20) DEFAULT NULL,       
	`STATUS` tinyint(1) DEFAULT NULL,        
	`ACTIVATIONDATETIME` bigint(20) DEFAULT NULL,       
	`CREATIONDATETIME` bigint(20) DEFAULT NULL,         
	`MESSAGETYPE` varchar(15) DEFAULT NULL, 
	`POPUPMESSAGE` tinyint(1) DEFAULT NULL, 
	`POPUPMESSAGETEXT` varchar(1024) DEFAULT NULL,     
	PRIMARY KEY (`MESSAGEID`)	   
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;  

--
-- Table structure for table `FILTERS`
--

CREATE TABLE `FILTERS` (
	`FILTERID` int(11) NOT NULL AUTO_INCREMENT,				 
	`MESSAGEID` int(11) NOT NULL,				
	`IPADDRESS` varchar(20) DEFAULT NULL,				       
	`PACKAGEID` varchar(50) DEFAULT NULL,				     
	`WATCHEDCHANNELID` varchar(30) DEFAULT NULL,			          
	`LOCATIONID` varchar(30) DEFAULT NULL,				    
	`SOFTWAREVERSION` varchar(30) DEFAULT NULL,				 
	`UIVERSION` varchar(30) DEFAULT NULL,				       
	`CURRENTUILANGUAGE` varchar(30) DEFAULT NULL,			          
	`HARDWAREVERSION` varchar(30) DEFAULT NULL,				
	`FIPSCODE` varchar(6) DEFAULT NULL,				         
	PRIMARY KEY (`FILTERID`),					       
	KEY `fk_mgs` (`MESSAGEID`),					     
	CONSTRAINT `filters_ibfk_1` FOREIGN KEY (`MESSAGEID`) REFERENCES `MESSAGES` (`MESSAGEID`)  ON DELETE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;  


--
-- Table structure for table `STBADDRESSING`
--

CREATE TABLE `STBADDRESSING` (					       
	`ID` int(11) NOT NULL AUTO_INCREMENT,				          
	`MACADDRESS` varchar(20) DEFAULT NULL,				        
	`MESSAGEID` int(11) NOT NULL,					 
	`MESSAGESTATUS` tinyint(1) DEFAULT NULL,				      
	PRIMARY KEY (`ID`),						    
	KEY `fk_mgs` (`MESSAGEID`),					       
	CONSTRAINT `stbaddressing_fk` FOREIGN KEY (`MESSAGEID`) REFERENCES `MESSAGES` (`MESSAGEID`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;					 

--
-- Table structure for table `MESSAGETYPES`
--

CREATE TABLE `MESSAGETYPES` (					       
	     `ID` int(11) NOT NULL,				          
	     `MESSAGETYPE` varchar(15),				        
	     PRIMARY KEY (`ID`)						    
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO MESSAGETYPES (ID, MESSAGETYPE) VALUES (1, 'Product');
INSERT INTO MESSAGETYPES (ID, MESSAGETYPE) VALUES (2, 'Service');
INSERT INTO MESSAGETYPES (ID, MESSAGETYPE) VALUES (3, 'CTA');


--
-- Table structure for table `DBVERSION`
--

CREATE TABLE DBVERSION (
	PRODUCTVERSION VARCHAR(50) NOT NULL,
	MINORVERSION INT(3) NOT NULL,
	CREATOR VARCHAR(50),
	DATECREATED DATE,
	DATEAPPLIED DATE NOT NULL,
	PRIMARY KEY (PRODUCTVERSION,MINORVERSION)
) ENGINE=InnoDB;

INSERT INTO DBVERSION (PRODUCTVERSION, MINORVERSION, CREATOR, DATECREATED, DATEAPPLIED)
     VALUES ('AVS 6.1', 0, 'RSI', STR_TO_DATE('2017-04-19', '%Y-%m-%d'), CURRENT_DATE());
	 
DROP TABLE IF EXISTS `push_messaging_service_instance`;

CREATE TABLE `push_messaging_service_instance` (
  `INSTANCE_ID` varchar(100) NOT NULL,
  `INSTANCE_NAME` varchar(50) NOT NULL,
  `PRIMARY_INSTANCE` tinyint(1) NOT NULL,
  `LAST_HEARTBEAT` bigint(13) NOT NULL,
  PRIMARY KEY (`INSTANCE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


DROP TABLE IF EXISTS `estimation_process_schedule`;

CREATE TABLE `estimation_process_schedule` (
  `SCHEDULE_ID` int(11) NOT NULL AUTO_INCREMENT,
  `SCHEDULED_TIME` bigint(13) NOT NULL,
  `STATUS` varchar(100) NOT NULL,
  PRIMARY KEY (`SCHEDULE_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8;

	 
COMMIT;
